#FlyManageBundle_admin_fly_manage_bundle_admin:
    #resource: "@FlyManageBundle/Controller/Admin/"
    #type:     admingenerator
    #prefix:   /manage

fly_flydb:
    resource: "@FlyFlydbBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

####### FOSUserBundle Routes ##########
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
####### FOSUserBundle Routes End ##########
    
#_assetic:
    #resource: .
    #type: assetic
