parameters:
#    fly_flydb.example.class: Fly\FlydbBundle\Example

services:
#    fly_flydb.example:
#        class: %fly_flydb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    fly.twig.fly_extension:
        class: Fly\FlydbBundle\Twig\FlyExtension
        tags:
            - { name: twig.extension }
            
    fly_user.registration.form.type:
        class: Fly\FlydbBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fly_user_registration }
            
    fly_user.profile.form.type:
        class: Fly\FlydbBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fly_user_profile }
            
